--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/angga7togk/PvPToggle-V2
build-by-default: true
branches:
- main
projects:
  PvPToggle-V2:
    path: ""
  icon:
    path: "swords.png"
...
