---
name: PvPToggle
main: angga7togk\pvptoggle\PvPToggle
version: 1.0.0
api: 5.0.0
author: Angga7Togk

permissions:
  pvptoggle.command:
    default: true
  pvptoggle.command.staff:
    default: op
...
